const assert=require('node:assert/strict');
(async()=>{
 const DB=require('./database.cjs')(),worker=(await import('../dist/server/index.js')).default;
 const env={DB,ASSETS:{fetch:request=>new Response(new URL(request.url).pathname)}};
 const admin=['REPLACE_WITH_VERIFIED_SITE_OWNER_SUBJECT','owner@example.test'],reader=['reader-site-subject','reader@example.test'];
 const req=(path='/api/workspace',method='GET',body,who=admin,cookie='',extra={})=>worker.fetch(new Request('https://cmdb.example'+path,{method,headers:{...(who?{'oai-authenticated-user-id':who[0],'oai-authenticated-user-email':who[1]}:{}),...(body?{'Content-Type':'application/json'}:{}),...(cookie?{cookie}:{}),...extra},body:body?JSON.stringify(body):undefined}),env);
 const get=async(path='/api/workspace',who=admin,cookie='')=>(await req(path,'GET',null,who,cookie)).json();
 assert.equal((await req('/api/workspace','GET',null,null)).status,401);
 assert.equal((await get('/api/workspace',reader)).role,'reader');
 assert.equal(DB.sql.prepare("SELECT count(*) n FROM app_users WHERE role='admin'").get().n,0);
 assert.equal((await req('/api/workspace','GET',null,null,'',{'oai-authenticated-user-email':admin[1]})).status,401);
 assert.equal((await get('/api/workspace',['different-subject',admin[1]])).role,'reader');
 let original=await get();assert.equal(original.role,'reader');assert.equal(original.state.hosts.length,require('../public/seed.json').hosts.length);
 assert.equal((await req('/api/workspace','PUT',{})).status,403);
 assert.equal((await req('/api/admin/workspace')).status,401);
 assert.equal((await req('/api/admin/users')).status,401);
 assert.equal((await req('/api/admin/auth/status','GET',null,reader)).status,403);
 assert.equal((await req('/api/admin/auth/setup','POST',{username:'reader',password:'a-long-test-password'},reader)).status,403);
 const adminPage=await req('/admin');
 assert.equal(adminPage.status,200);
 assert.equal(adminPage.headers.get('location'),null);
 assert.match(await adminPage.text(),/<title>BSK · Infrastructure workspace<\/title>/);
 console.log('PASS default inventory read-only even for owner; /admin route; no administration APIs before password sign-in');
 assert.equal((await get('/api/admin/auth/status')).setupRequired,true);
 const credentials={username:'qa-admin',password:'Only-For-Isolated-Tests-2026'};
 assert.equal((await req('/api/admin/auth/setup','POST',credentials,admin,'',{origin:'https://evil.test'})).status,403);
 assert.equal((await req('/api/admin/auth/setup','POST',{username:'qa-admin',password:'short'})).status,400);
 assert.equal((await req('/api/admin/auth/setup','POST',credentials)).status,200);
 assert.equal((await req('/api/admin/auth/setup','POST',credentials)).status,409);
 assert.equal((await get('/api/admin/auth/status')).setupRequired,false);
 assert(!JSON.stringify(DB.sql.prepare('SELECT * FROM admin_credentials').get()).includes(credentials.password));
 assert.equal((await req('/api/admin/auth/login','POST',{...credentials,password:'wrong'})).status,401);
 const login=await req('/api/admin/auth/login','POST',credentials);assert.equal(login.status,200);
 assert.match(login.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Strict/);
 const cookie=login.headers.get('set-cookie').split(';')[0];
 assert.equal((await get('/api/admin/workspace',admin,cookie)).role,'admin');
 assert.equal((await get('/api/workspace',admin,cookie)).role,'reader');
 assert.equal((await req('/api/admin/workspace','GET',null,reader,cookie)).status,401);
 console.log('PASS protected setup, salted password hash, incorrect-password rejection, session cookie, identity binding');
 const ag=()=>get('/api/admin/workspace',admin,cookie);
 const put=snapshot=>req('/api/admin/workspace','PUT',{state:snapshot.state,revision:snapshot.revision,change:{action:'QA inventory change'}},admin,cookie);
 const users=(await get('/api/admin/users',admin,cookie)).users,owner=users.find(u=>u.id===admin[0]);
 for(const edit of [{role:'reader',enabled:true},{role:'admin',enabled:false}])assert.equal((await req('/api/admin/users','PUT',{id:owner.id,version:owner.version,...edit},admin,cookie)).status,409);
 let snapshot=await ag();const stale=structuredClone(snapshot);
 snapshot.state.applications.push({id:'qa-app',name:'QA App',owner:'QA',description:'',source:'test'});assert.equal((await put(snapshot)).status,200);assert.equal((await put(stale)).status,409);
 snapshot=await ag();const record=Object.fromEntries(globalThis.CmdbModel.fieldKeys.map(k=>[k,'']));Object.assign(record,{server:'QA-HOST',application:'QA App',applicationId:'qa-app',owner:'QA',asset:'QA-1'});
 snapshot.state.hosts.push({id:'qa-host',server:'QA-HOST',type:'physical',vmware:{vcenter:'',cluster:'',esxiHost:'',vmName:''},sample:true,records:[record],placements:[],connections:[]});snapshot.state.racks.push({id:'qa-rack',name:'QA rack',room:'QA room',aisle:'QA aisle',units:42,sample:true});assert.equal((await put(snapshot)).status,200);
 snapshot=await ag();snapshot.state.hosts.find(h=>h.id==='qa-host').placements=[{rackId:'qa-rack',unit:1,height:2}];assert.equal((await put(snapshot)).status,200);
 snapshot=await ag();snapshot.state.applications=snapshot.state.applications.filter(a=>a.id!=='qa-app');assert.equal((await put(snapshot)).status,400);
 snapshot=await ag();snapshot.state.hosts.find(h=>h.id==='qa-host').type='virtual';assert.equal((await put(snapshot)).status,400);
 snapshot=await ag();snapshot.state.racks=snapshot.state.racks.filter(r=>r.id!=='qa-rack');snapshot.state.hosts=snapshot.state.hosts.filter(h=>h.id!=='qa-host');assert.equal((await put(snapshot)).status,400);
 snapshot=await ag();snapshot.state.racks=snapshot.state.racks.filter(r=>r.id!=='qa-rack');snapshot.state.hosts.find(h=>h.id==='qa-host').placements=[];assert.equal((await put(snapshot)).status,200);
 snapshot=await ag();assert(snapshot.state.hosts.find(h=>h.id==='qa-host'));snapshot.state.hosts.find(h=>h.id==='qa-host').records[0].owner='QA edited';assert.equal((await put(snapshot)).status,200);
 snapshot=await ag();snapshot.state.hosts=snapshot.state.hosts.filter(h=>h.id!=='qa-host');assert.equal((await put(snapshot)).status,200);
 snapshot=await ag();snapshot.state.applications=snapshot.state.applications.filter(a=>a.id!=='qa-app');assert.equal((await put(snapshot)).status,200);
 assert.deepEqual((await ag()).state.hosts,original.state.hosts);assert.deepEqual((await ag()).state.racks,original.state.racks);
 console.log('PASS password-authenticated CRUD, stale writes, last-admin protection, rack deletion retention, original inventory equality');
 const backup=await get('/api/admin/backup',admin,cookie);snapshot=await ag();assert.equal((await req('/api/admin/restore','PUT',{state:backup,revision:snapshot.revision},admin,cookie)).status,200);
 const history=await get('/api/admin/history',admin,cookie);assert(history.events.every(e=>e.actor_id===admin[0]));assert(history.events.some(e=>Array.isArray(e.details)&&e.details.some(d=>d.kind==='hosts'&&d.before&&d.after)));
 const r=users.find(u=>u.id===reader[0]);assert.equal((await req('/api/admin/users','PUT',{id:r.id,version:0,role:'admin',enabled:true},admin,cookie)).status,200);
 assert.equal((await req('/api/admin/workspace','GET',null,reader)).status,401);
 assert.equal((await req('/api/admin/auth/setup','POST',{username:'qa-reader',password:'Password-For-Second-Admin-Only'},reader)).status,200);
 const secondLogin=await req('/api/admin/auth/login','POST',{username:'qa-reader',password:'Password-For-Second-Admin-Only'},reader);const secondCookie=secondLogin.headers.get('set-cookie').split(';')[0];
 assert.equal((await req('/api/admin/users','PUT',{id:r.id,version:1,role:'reader',enabled:true},admin,cookie)).status,200);
 assert.equal((await req('/api/admin/workspace','GET',null,reader,secondCookie)).status,401);
 assert.equal(DB.sql.prepare('SELECT count(*) n FROM admin_sessions WHERE user_id=?').get(reader[0]).n,0);
 assert.equal((await req('/api/admin/auth/logout','POST',null,admin,cookie)).status,200);
 assert.equal((await req('/api/admin/workspace','GET',null,admin,cookie)).status,401);
 const again=await req('/api/admin/auth/login','POST',credentials);assert.equal(again.status,200);const expCookie=again.headers.get('set-cookie').split(';')[0];DB.sql.prepare('UPDATE admin_sessions SET expires_at=0').run();assert.equal((await req('/api/admin/workspace','GET',null,admin,expCookie)).status,401);
 for(let i=0;i<5;i++)assert.equal((await req('/api/admin/auth/login','POST',{...credentials,password:'wrong'})).status,401);
 assert.equal((await req('/api/admin/auth/login','POST',credentials)).status,429);
 console.log('PASS backup/restore, attributed history, role revocation, logout, expired sessions, login rate limit');
 DB.sql.prepare("DELETE FROM access_metadata WHERE key='owner-password-reset-20260922'").run();
 assert.equal((await get('/api/admin/auth/status')).setupRequired,true);
 assert.equal(DB.sql.prepare('SELECT count(*) n FROM admin_sessions WHERE user_id=?').get(admin[0]).n,0);
 assert.equal(DB.sql.prepare('SELECT count(*) n FROM admin_credentials WHERE user_id=?').get(admin[0]).n,0);
 const newCredentials={username:'qa-new-admin',password:'Replacement-Password-Only-2026'};
 assert.equal((await req('/api/admin/auth/setup','POST',newCredentials)).status,200);
 assert.equal((await get('/api/admin/auth/status')).setupRequired,false);
 assert.equal((await req('/api/admin/auth/login','POST',credentials)).status,401);
 assert.equal((await req('/api/admin/auth/login','POST',newCredentials)).status,200);
 assert.deepEqual((await get()).state.hosts,original.state.hosts);
 console.log('PASS missing identity fails closed; same-email different subject stays reader; reset revokes sessions, preserves inventory, runs once, and accepts a replacement password');
 DB.sql.close();
})().catch(e=>{console.error(e);process.exit(1)});
