import test from 'node:test';
import assert from 'node:assert/strict';
import {hashPassword,verifyPassword,cookieToken,sessionCookie} from '../onprem/security.mjs';
import {createApp} from '../onprem/server.mjs';
test('health check reports whether host form and room catalog reached the image',async()=>{
 const app=createApp({query:async()=>[]},{origin:'http://127.0.0.1:39094',allowHttp:true});
 await new Promise(resolve=>app.listen(39094,'127.0.0.1',resolve));
 try{
  const result=await fetch('http://127.0.0.1:39094/healthz');
  assert.equal(result.status,200);
  assert.deepEqual(await result.json(),{ok:true,ui:{hostForm:true,computerRooms:true}});
 }finally{await new Promise(resolve=>app.close(resolve))}
});
test('password hashing and cookie security',async()=>{const password='A-long-test-password-2026';const a=await hashPassword(password),b=await hashPassword(password);assert.notEqual(a,b);assert(!a.includes(password));assert(await verifyPassword(password,a));assert(!await verifyPassword('wrong',a));await assert.rejects(hashPassword('short'));assert.match(sessionCookie('abc',true),/HttpOnly; SameSite=Strict; Max-Age=1800; Secure/);assert.equal(cookieToken({headers:{cookie:'cmdb_session='+'a'.repeat(64)}}),'a'.repeat(64))});
test('public inventory read; no identity-header trust for admin; same-origin writes; explicit static allowlist',async()=>{const state={schemaVersion:2,hosts:[],racks:[],applications:[],audit:['private audit'],sources:[],notes:[],importedAt:'2026-09-22'};const conn={beginTransaction:async()=>{},commit:async()=>{},rollback:async()=>{},release:()=>{},query:async sql=>{if(sql.startsWith('SELECT id FROM cmdb_lock'))return[];if(sql.startsWith('SELECT data,revision'))return[{data:JSON.stringify(state),revision:1,updated_at:'2026-09-22T00:00:00.000Z'}];if(sql.startsWith('SELECT data FROM applications'))return[];return[]}};const db={query:async()=>[],getConnection:async()=>conn};const app=createApp(db,{origin:'http://127.0.0.1:39091',allowHttp:true});await new Promise(r=>app.listen(39091,'127.0.0.1',r));try{const base='http://127.0.0.1:39091';const publicRead=await fetch(base+'/api/workspace',{headers:{'oai-authenticated-user-id':'admin','oai-authenticated-user-email':'owner@example.test'}});assert.equal(publicRead.status,200);const publicData=await publicRead.json();assert.equal(publicData.role,'reader');assert.deepEqual(publicData.state.audit,[]);assert.equal((await fetch(base+'/api/admin/users',{headers:{'oai-authenticated-user-id':'admin','oai-authenticated-user-email':'owner@example.test'}})).status,401);assert.equal((await fetch(base+'/api/auth/login',{method:'POST',headers:{origin:'https://evil.example','content-type':'application/json'},body:'{}'})).status,403);for(const path of ['/seed.json','/.env','/server/access.js'])assert.equal((await fetch(base+path)).status,404);const login=await fetch(base+'/admin',{redirect:'manual'});assert.equal(login.status,302);assert.equal(login.headers.get('location'),'/login?return_to=%2Fadmin')}finally{await new Promise(r=>app.close(r))}});
